language: php

php:
  - 5.6
  - 7.0
  
install: travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

notifications:
  slack: cutcode:DU2WYQ5RGD4bBlXxsXeRPUki

after_success:
    - travis_retry php vendor/bin/coveralls
    # or enable logging
    - travis_retry php vendor/bin/coveralls -v